# Generated by Django 4.0 on 2021-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_capacity', models.IntegerField(blank=True)),
                ('current_capacity', models.IntegerField(blank=True)),
            ],
        ),
    ]
